<?php

$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
$session = Mage::getSingleton('checkout/session');
if (isset($order) && $order->getId() && ($order->getShippingMethod() == "urbit_onehour_urbit_onehour" || $order->getShippingMethod() == "urbit_onehour_urbit_specific")) {
    $response = $session->getUrbitResponse();
    ?>

    <div id="urbit_success">
        <img src="<?php echo $this->getSkinUrl('images/vaimo/urbit/urb-it_text_50px.png'); ?>" />
        <div class="box">
            <h4><?php echo $this->__("urb-it - delivery notice:"); ?></h4>

            <p><?php echo $this->__("If a mobile number is registered on the order you will receive an SMS with all details of the delivery."); ?></p>

            <?php if ($response == null || isset($response["order_number"]) == false) { ?>
                <p style="color:#ff0000;"><?php echo $this->__("Error: Something went wrong in the communication with urb-it. <b>Please call us to schedule a new delivery.</b>") ?></p>
                <p><?php echo $response["message"]; ?></p>
            <?php } else { ?>
                <p><?php echo $this->__("Order number:")?> <?php echo $response["order_number"]; ?></p>
            <?php } ?>
        </div>
    </div>

<?php
    //unset form fields
    $session->unsetData('shipping_comment');
    $session->unsetData('shipping_day');
    $session->unsetData('shipping_hour');
    $session->unsetData('shipping_minute');
    $session->unsetData('shipping_telephone');
    $session->unsetData('shipping_day');

    //unset response
    $session->unsUrbitResponse();
}
?>